### ISSUE TITLE
NO such file or directory

### ISSUE THREAD

**Issue by ldm584** [PathPlanning/TO-AA-SIPP#1]
#include <boost/multi_index_container.hpp>
#include <boost/multi_index/member.hpp>
#include <boost/multi_index/ordered_index.hpp>
#include <boost/multi_index/hashed_index.hpp>
#include <boost/multi_index/composite_key.hpp>
#include <boost/tuple/tuple.hpp>

**Comment by aandreychuk** [comment]
You need to download Boost.
It's an external library.

**Comment by ldm584** [comment]
Thank you very much. I would also like to know that this is the main difference from code ( https://github.com/PathPlanning/AA-SIPP-m) )

**Comment by aandreychuk** [comment]
TO-AA-SIPP is a single-agent any-angle optimal planner that plans amidst dynamic obstacles. For more details, you can look through [https://ojs.aaai.org/index.php/ICAPS/article/view/15986](ICAPS-21)
AA-SIPP(m) is a multi-agent planner. It supports any-angle moves and dynamic obstacles but has no optimality guarantees.
